/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package petstoreserver
// OrderStatus : Order Status
type OrderStatus string

// List of OrderStatus
const (
	PLACED OrderStatus = "placed"
	APPROVED OrderStatus = "approved"
	DELIVERED OrderStatus = "delivered"
)

// AssertOrderStatusRequired checks if the required fields are not zero-ed
func AssertOrderStatusRequired(obj OrderStatus) error {
	return nil
}

// AssertRecurseOrderStatusRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of OrderStatus (e.g. [][]OrderStatus), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseOrderStatusRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aOrderStatus, ok := obj.(OrderStatus)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertOrderStatusRequired(aOrderStatus)
	})
}
