/**
 * Example
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Cat } from './Cat';
import { Dog } from './Dog';
import { HttpFile } from '../http/http';

export class InlineBody {
    'hunts'?: boolean;
    'age'?: number;
    'bark'?: boolean;
    'breed'?: InlineBodyBreedEnum;

    static readonly discriminator: string | undefined = "petType";

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hunts",
            "baseName": "hunts",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "age",
            "baseName": "age",
            "type": "number",
            "format": ""
        },
        {
            "name": "bark",
            "baseName": "bark",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "breed",
            "baseName": "breed",
            "type": "InlineBodyBreedEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineBody.attributeTypeMap;
    }
    
    public constructor() {
        this.petType = "InlineBody";
    }
}


export type InlineBodyBreedEnum = "Dingo" | "Husky" | "Retriever" | "Shepherd" ;

