"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import petstore_api
from petstore_api.model.post_inline_additional_properties_payload_body_array_data_items import PostInlineAdditionalPropertiesPayloadBodyArrayDataItems
globals()['PostInlineAdditionalPropertiesPayloadBodyArrayDataItems'] = PostInlineAdditionalPropertiesPayloadBodyArrayDataItems
from petstore_api.model.post_inline_additional_properties_payload_body import PostInlineAdditionalPropertiesPayloadBody


class TestPostInlineAdditionalPropertiesPayloadBody(unittest.TestCase):
    """PostInlineAdditionalPropertiesPayloadBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostInlineAdditionalPropertiesPayloadBody(self):
        """Test PostInlineAdditionalPropertiesPayloadBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostInlineAdditionalPropertiesPayloadBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
