/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package petstoreserver
// PetStatus : pet status in the store
type PetStatus string

// List of PetStatus
const (
	AVAILABLE PetStatus = "available"
	PENDING PetStatus = "pending"
	SOLD PetStatus = "sold"
)

// AssertPetStatusRequired checks if the required fields are not zero-ed
func AssertPetStatusRequired(obj PetStatus) error {
	return nil
}

// AssertRecursePetStatusRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PetStatus (e.g. [][]PetStatus), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePetStatusRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPetStatus, ok := obj.(PetStatus)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPetStatusRequired(aPetStatus)
	})
}
