/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package petstoreserver

type StatusItems string

// List of StatusItems
const (
	AVAILABLE StatusItems = "available"
	PENDING StatusItems = "pending"
	SOLD StatusItems = "sold"
)

// AssertStatusItemsRequired checks if the required fields are not zero-ed
func AssertStatusItemsRequired(obj StatusItems) error {
	return nil
}

// AssertRecurseStatusItemsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of StatusItems (e.g. [][]StatusItems), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseStatusItemsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aStatusItems, ok := obj.(StatusItems)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertStatusItemsRequired(aStatusItems)
	})
}
